In [2]:
import numpy as np

In [3]:
array_list = [1,2,3]
array_np = np.array([1,2,3])
array_list

array([1, 2, 3])

In [4]:
array_np

array([1, 2, 3])

In [5]:
array_list * 2

[1, 2, 3, 1, 2, 3]

In [6]:
array_np * 2

array([2, 4, 6])

In [7]:
array_np_1 = np.array([1,2])
array_np_2 = np.array([3,4])

array_np_1 * array_np_2

array([3, 8])

In [8]:
np.sum(array_np_1 * array_np_2)

11

In [9]:
np.dot(array_np_1, array_np_2)

11

In [10]:
matrix_a = np.array([[1,2], [3,4]])
list_a = [[1,2], [3,4]]

In [11]:
matrix_a

array([[1, 2],
       [3, 4]])

In [12]:
list_a

[[1, 2], [3, 4]]

In [14]:
matrix_a[:,0]

array([1, 3])

In [15]:
matrix_a.T

array([[1, 3],
       [2, 4]])

In [16]:
np.exp(matrix_a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [17]:
np.exp(list_a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [19]:
matrix_b = np.array([[4,3], [2,1]])
matrix_b

array([[4, 3],
       [2, 1]])

In [20]:
matrix_a.dot(matrix_b)

array([[ 8,  5],
       [20, 13]])

In [21]:
matrix_a @ matrix_b

array([[ 8,  5],
       [20, 13]])